USE `zynervox`;

-- Administrative configuration inspired by asterisk.vicidial_campaigns.
-- Additive and repeatable; max_channels is specific to Bot IVR.
ALTER TABLE zynervox_bot_campaigns
  ADD COLUMN IF NOT EXISTS campaign_description VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS user_group VARCHAR(20) NOT NULL DEFAULT '---ALL---',
  ADD COLUMN IF NOT EXISTS dial_method ENUM('MANUAL','RATIO','ADAPT_HARD_LIMIT','ADAPT_TAPERED','ADAPT_AVERAGE') NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS lead_order ENUM('DOWN','UP','RANDOM') NOT NULL DEFAULT 'DOWN',
  ADD COLUMN IF NOT EXISTS dial_statuses VARCHAR(255) NOT NULL DEFAULT 'NEW',
  ADD COLUMN IF NOT EXISTS hopper_level INT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS auto_dial_level DECIMAL(5,2) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dial_timeout TINYINT UNSIGNED NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS dial_prefix VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS campaign_cid VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS campaign_recording ENUM('NEVER','ONDEMAND','ALLCALLS','ALLFORCE') NOT NULL DEFAULT 'NEVER',
  ADD COLUMN IF NOT EXISTS max_channels SMALLINT UNSIGNED NOT NULL DEFAULT 1;
