ALTER TABLE zynervox_bot_call_attempts
 ADD COLUMN IF NOT EXISTS linked_id VARCHAR(80) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS caller_channel VARCHAR(160) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS callee_channel VARCHAR(160) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS callee_unique_id VARCHAR(80) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS origin_prefix VARCHAR(20) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS carrier VARCHAR(60) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS answered_at DATETIME NULL,
 ADD COLUMN IF NOT EXISTS duration_seconds INT UNSIGNED NULL,
 ADD COLUMN IF NOT EXISTS billsec INT UNSIGNED NULL,
 ADD COLUMN IF NOT EXISTS end_source VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE zynervox_bot_call_attempts ADD COLUMN IF NOT EXISTS missing_since DATETIME NULL;
CREATE TABLE IF NOT EXISTS zynervox_bot_call_events (
 event_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 call_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 event_type VARCHAR(20) NOT NULL,
 occurred_at DATETIME NOT NULL,
 received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 payload_json LONGTEXT NOT NULL,
 KEY idx_call_events(call_id,occurred_at),
 CHECK(JSON_VALID(payload_json))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
