CREATE TABLE IF NOT EXISTS v2_phones (
 extension VARCHAR(20) NOT NULL PRIMARY KEY,
 login VARCHAR(160) NOT NULL,
 pass VARCHAR(160) NOT NULL,
 fullname VARCHAR(160) NOT NULL DEFAULT '',
 outbound_cid VARCHAR(160) NOT NULL DEFAULT '',
 active CHAR(1) NOT NULL DEFAULT 'Y',
 protocol VARCHAR(20) NOT NULL DEFAULT 'PJSIP',
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 user_group VARCHAR(160) NOT NULL DEFAULT '---ALL---'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
