ALTER TABLE bot_ivr_flows
  ADD COLUMN IF NOT EXISTS start_node_id VARCHAR(64) NOT NULL DEFAULT '' AFTER name,
  ADD COLUMN IF NOT EXISTS published_at DATETIME NULL AFTER updated_at,
  ADD COLUMN IF NOT EXISTS published_sha256 CHAR(64) NULL AFTER published_at;

CREATE TABLE IF NOT EXISTS bot_ivr_flow_nodes (
 flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,type VARCHAR(32) NOT NULL,message VARCHAR(240) NOT NULL DEFAULT '',
 audio VARCHAR(255) NOT NULL DEFAULT '',audio_text TEXT NOT NULL,audio_hash CHAR(64) NOT NULL DEFAULT '',audio_status VARCHAR(16) NOT NULL DEFAULT 'pending',
 capture_mode VARCHAR(16) NOT NULL DEFAULT 'date',variable_name VARCHAR(64) NOT NULL DEFAULT '',bridge_id VARCHAR(64) NOT NULL DEFAULT '',
 bridge_category VARCHAR(64) NOT NULL DEFAULT '',bridge_text VARCHAR(240) NOT NULL DEFAULT '',execute_url VARCHAR(4000) NOT NULL DEFAULT '',
 execute_method VARCHAR(8) NOT NULL DEFAULT 'GET',anexo VARCHAR(64) NOT NULL DEFAULT '',contexto VARCHAR(64) NOT NULL DEFAULT '',prioridad TINYINT UNSIGNED NOT NULL DEFAULT 1,
 next_node_id VARCHAR(64) NOT NULL DEFAULT '',fallback_node_id VARCHAR(64) NOT NULL DEFAULT '',timeout_ms INT UNSIGNED NOT NULL DEFAULT 6000,
 retry_count TINYINT UNSIGNED NOT NULL DEFAULT 0,retry_text VARCHAR(500) NOT NULL DEFAULT '',retry_audio VARCHAR(255) NOT NULL DEFAULT '',retry_audio_hash CHAR(64) NOT NULL DEFAULT '',
 position_x SMALLINT UNSIGNED NOT NULL DEFAULT 40,position_y SMALLINT UNSIGNED NOT NULL DEFAULT 40,compose_provider VARCHAR(32) NOT NULL DEFAULT 'deepgram',
 composite_hash CHAR(64) NOT NULL DEFAULT '',composite_status VARCHAR(16) NOT NULL DEFAULT 'pending',
 PRIMARY KEY(flow_code,node_id),CONSTRAINT fk_ivr_nodes_flow FOREIGN KEY(flow_code) REFERENCES bot_ivr_flows(flow_code) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_edges (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,edge_key VARCHAR(8) NOT NULL,target_node_id VARCHAR(64) NOT NULL,PRIMARY KEY(flow_code,node_id,edge_key),CONSTRAINT fk_ivr_edges_node FOREIGN KEY(flow_code,node_id) REFERENCES bot_ivr_flow_nodes(flow_code,node_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_intents (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,intent_id VARCHAR(64) NOT NULL,match_type VARCHAR(32) NOT NULL DEFAULT 'contains_any',priority SMALLINT UNSIGNED NOT NULL DEFAULT 100,target_node_id VARCHAR(64) NOT NULL,fuzzy TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(flow_code,node_id,intent_id),CONSTRAINT fk_ivr_intents_node FOREIGN KEY(flow_code,node_id) REFERENCES bot_ivr_flow_nodes(flow_code,node_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_intent_phrases (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,intent_id VARCHAR(64) NOT NULL,phrase_order SMALLINT UNSIGNED NOT NULL,phrase VARCHAR(120) NOT NULL,PRIMARY KEY(flow_code,node_id,intent_id,phrase_order),CONSTRAINT fk_ivr_phrases_intent FOREIGN KEY(flow_code,node_id,intent_id) REFERENCES bot_ivr_flow_intents(flow_code,node_id,intent_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_ranges (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,range_order SMALLINT UNSIGNED NOT NULL,min_value INT NULL,max_value INT NULL,label VARCHAR(120) NOT NULL DEFAULT '',target_node_id VARCHAR(64) NOT NULL,PRIMARY KEY(flow_code,node_id,range_order),CONSTRAINT fk_ivr_ranges_node FOREIGN KEY(flow_code,node_id) REFERENCES bot_ivr_flow_nodes(flow_code,node_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_segments (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,segment_order SMALLINT UNSIGNED NOT NULL,segment_id VARCHAR(40) NOT NULL,text_value VARCHAR(500) NOT NULL,pause_after_ms SMALLINT UNSIGNED NOT NULL DEFAULT 0,hash_value CHAR(64) NOT NULL DEFAULT '',cached TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(flow_code,node_id,segment_order),CONSTRAINT fk_ivr_segments_node FOREIGN KEY(flow_code,node_id) REFERENCES bot_ivr_flow_nodes(flow_code,node_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bot_ivr_flow_sql_fields (flow_code CHAR(2) NOT NULL,node_id VARCHAR(64) NOT NULL,column_name VARCHAR(64) NOT NULL,template_value VARCHAR(4000) NOT NULL,PRIMARY KEY(flow_code,node_id,column_name),CONSTRAINT fk_ivr_fields_node FOREIGN KEY(flow_code,node_id) REFERENCES bot_ivr_flow_nodes(flow_code,node_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
